### ISSUE TITLE
All except one

### ISSUE THREAD

**Issue by klemenoslaj** [aaronpowell/db.js#72] opened 2014-05-20 09:59 UTC
Is it possible to filter all values except one?
For an example, we have index fruit and its values apple, pineapple, grapes.

Now I wish to have all results except those with fruit value apple(!= apple). Is this possible?

**Comment by brettz9** [comment] 2016-03-27 05:51
This looks like a dupe of #40.

**Comment by brettz9** [comment] 2016-03-28 02:16
Aaron's solution is possible now (see the `query.js` file under "index.multiEntry" [here](https://github.com/aaronpowell/db.js/blob/master/tests/specs/query.js#L711)), but it would require an explicit whitelist. Otherwise, you could use a filter.

**Closed** 2016-03-28 04:50 UTC
